### ISSUE TITLE
 Extractfield on matrix of struct

### ISSUE THREAD

**Issue by hardyscc** [palexang/food-101#1]
under pipline.m line 33, I think the extractfield function shouldn't work on matrix of struct, do u know what is the problem? Anyway your code is so helpful!!

  Error in extractfield (line 33)
  validateattributes(S,    {'struct'}, {'vector'}, fcnname, 'S', 1)

**Comment by alpapado** [comment]
Hi

How do you mean? As far I as I know it seems to work.

Bear in mind it is not the extractfield function that comes with matlab
but a custom one, that you can find under src/common

On 13/06/2016 12:45 μμ, hardyscc wrote:

> under pipline.m line 33, I think the extractfield function shouldn't
> work on matrix of struct, do u know what is the problem? Anyway your
> code is so helpful!!
> 
> Error in extractfield (line 33)
> validateattributes(S, {'struct'}, {'vector'}, fcnname, 'S', 1)
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> https://github.com/palexang/food-101/issues/1, or mute the thread
> https://github.com/notifications/unsubscribe/AK5cZwYUKvqMr_POpzSVSc8CZ_oZeTv-ks5qLSbBgaJpZM4I0KJt.

## 

/Alexandros Papadopoulos/

**Comment by hardyscc** [comment]
Dear Alex

Thanks for your quick reply.  Refer to your src/common/extractfield.m line:38, the validateattributes will always throw error if the first argument is not type of struct or vector, do I missed anything?

**Comment by alpapado** [comment]
Yes you are correct. It doesn't work for a matrix of structs so I have
to convert the matrix into a vector first.
I had it fixed but now that I look at it, I did not push the changes.
Should be ok now

Thanks for letting me know.

By the way would you like to tell me what you are using it for? Just out
of curiosity

On 13/06/2016 04:34 μμ, hardyscc wrote:

> Dear Alex
> 
> Thanks for your quick reply. Refer to your src/common/extractfield.m
> line:38, the validateattributes will always throw error if the first
> argument is not type of struct or vector, do I missed anything?
> 
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> https://github.com/palexang/food-101/issues/1#issuecomment-225582101, or
> mute the thread
> https://github.com/notifications/unsubscribe/AK5cZ24CjAq4klGSCs0ilueuWWWHFySEks5qLVyCgaJpZM4I0KJt.

## 

/Alexandros Papadopoulos/

**Comment by hardyscc** [comment]
Dear Alex

I am currently doing research on the topic of Food Recognition, and found out this interesting publication from ETH Zurich CVL, luckily I saw your matlab implementation on github, so would like to use your code as a reference to understand the paper more deeply. 

Furthermore I planned to build a caloris calculator mobile app, but it is still too early to say anything.

Thank you so much for your help.

**Comment by alpapado** [comment]
Cool. Glad to be of assistance.

Good luck in your future endeavors :)

On 14/06/2016 10:19 πμ, hardyscc wrote:

> Dear Alex
> 
> I am currently doing research on the topic of Food Recognition, and
> found out this interesting publication from ETH Zurich CVL, luckily I
> saw your matlab implementation on github, so would like to use your
> code as a reference to understand the paper more deeply.
> 
> Furthermore I planned to build a caloris calculator mobile app, but it
> is still too early to say anything.
> 
> Thank you so much for your help.
> 
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> https://github.com/palexang/food-101/issues/1#issuecomment-225799232, or
> mute the thread
> https://github.com/notifications/unsubscribe/AK5cZyBWB6S9hGY078P4fMUcY8SL8tUZks5qLlYDgaJpZM4I0KJt.

## 

/Alexandros Papadopoulos/
